GymFit/config/routes.rb
Rails.application.routes.draw do
  get 'admins/show'
  get 'users/show'
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins
  resources :trainings
  resources :exercises
  resources :obstacles
  resources :goals
  get 'homepage/index'
  get 'info' => 'information#index'
  get 'listaalunos' => 'users#list_users' 

  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GymFit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

GymFit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GymFit/app/models/exercise.rb
class Exercise < ApplicationRecord
   belongs_to :training
end

GymFit/app/models/goal.rb
class Goal < ApplicationRecord
end

GymFit/app/models/obstacle.rb
class Obstacle < ApplicationRecord
end

GymFit/app/models/training.rb
class Training < ApplicationRecord
   has_many :exercises
end

GymFit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :training
  has_one :goal
  has_one :obstacle

end

GymFit/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
    @admin = Admin.find(params[ :id])
  end
end

GymFit/app/controllers/edition_controller.rb
class EditionController < ApplicationController
  def index
  end
end

GymFit/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:goal)
    end
end

GymFit/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

GymFit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[ :id])
  end
  def list_users
    @user = User.find(params[ :id])
  end
end

GymFit/app/helpers/admins_helper.rb
module AdminsHelper
end

GymFit/app/helpers/application_helper.rb
module ApplicationHelper
end

GymFit/app/helpers/edition_helper.rb
module EditionHelper
end

GymFit/app/helpers/exercises_helper.rb
module ExercisesHelper
end

GymFit/app/helpers/goals_helper.rb
module GoalsHelper
end

GymFit/app/helpers/homepage_helper.rb
module HomepageHelper
end

GymFit/app/helpers/information_helper.rb
module InformationHelper
end

GymFit/app/helpers/obstacles_helper.rb
module ObstaclesHelper
end

GymFit/app/helpers/trainings_helper.rb
module TrainingsHelper
end

GymFit/app/helpers/users_helper.rb
module UsersHelper
end

GymFit/app/views/edition/index.html.erb
<h1>Edition#index</h1>
<p>Find me in app/views/edition/index.html.erb</p>

GymFit/app/views/homepage/index.html.erb
<% if user_signed_in?%>
   <div class= "big-banner">
   <div class="navbar sticky-top navbar-light bg-light">
   <a class="navbar-brand" href=>GymFit</a>
   <form class="form-inline">
   <a class="btn btn-outline-success" href="/trainings" role="button">
   Treinos
   </a>
   <a class="btn btn-outline-primary" href= "/users/1" role="button">
      Área do Aluno
   </a>
   <li><%=link_to "Sair", destroy_admin_session_path, method: :delete%></li>
   </div>
   </a>
   </div>
   </div>
   </form>

   </ul>
<% else %>
   <div class= "big-banner">
   <div class="navbar sticky-top navbar-light bg-light">
   <a class="navbar-brand" href=>GymFit</a>
   <form class="form-inline">

   <a class="btn btn-outline-primary" href= "/users/sign_in" role="button">
      Entrar
   </a>
   <div style="padding-left: 10px;">
   <a class="btn btn-outline-success" href="/users/sign_up" role="button">
      Cadastrar
   </a>
   <a class="btn btn-outline-warning" href="/trainings" role="button">
      Treinos
   </a>
      </a>
      </div>
   </div>
   </div>
    </form>
    </div>
   </ul>
<%end%>

<% if admin_signed_in?%>
<div class = "white_bg4">
   <ul>
      <p><b> Área do Administrador </p></b>
      <li><%=link_to "Informações Gerais", 'info'%></li>
      <li><%=link_to "Sair", destroy_admin_session_path, method: :delete%></li>

   </ul>
   </div>
<%end%>

<div class="white_bg">
  <div class = "titulo">
    <b>GymFit</b>
    </div>
    <div class = "texto">

      <p>A GymFit® é uma rede de academias presente em mais de 65 países. Com altos padrões de qualidade, 
      é possível atingir seus objetivos em pouco tempo. Na GymFit, você conta com professores altamente qualificados e
      equipamentos diversos e de alta segurança. </p> 
      <p>Neste site, é possível cadastrar-se, ter acesso aos seus treinos, a equipamentos, ao progresso do aluno etc.</p>
      <p>Venha fazer parte dessa familia, cadastre-se em nosso site e aproveite as vantagens de ser aluno da GymFit.</p>
      
    </div>
</div>