GymFit/config/routes.rb
Rails.application.routes.draw do
  get 'admins/show'
  get 'users/show'
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins
  resources :trainings
  resources :exercises
  resources :obstacles
  resources :goals
  get 'homepage/index'
  get 'info' => 'information#index'
  get 'listaalunos' => 'users#list_users' 

  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GymFit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

GymFit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GymFit/app/models/exercise.rb
class Exercise < ApplicationRecord
   belongs_to :training
end

GymFit/app/models/goal.rb
class Goal < ApplicationRecord
end

GymFit/app/models/obstacle.rb
class Obstacle < ApplicationRecord
end

GymFit/app/models/training.rb
class Training < ApplicationRecord
   has_many :exercises
end

GymFit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :training
  has_one :goal
  has_one :obstacle

end

GymFit/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
    @admin = Admin.find(params[ :id])
  end
end

GymFit/app/controllers/edition_controller.rb
class EditionController < ApplicationController
  def index
  end
end

GymFit/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:goal)
    end
end

GymFit/app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.all
    @trainings = Training.all
    @exercises = Exercise.all
  end
end

GymFit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[ :id])
  end
  def list_users
    @user = User.find(params[ :id])
  end
end

GymFit/app/helpers/admins_helper.rb
module AdminsHelper
end

GymFit/app/helpers/application_helper.rb
module ApplicationHelper
end

GymFit/app/helpers/edition_helper.rb
module EditionHelper
end

GymFit/app/helpers/exercises_helper.rb
module ExercisesHelper
end

GymFit/app/helpers/goals_helper.rb
module GoalsHelper
end

GymFit/app/helpers/homepage_helper.rb
module HomepageHelper
end

GymFit/app/helpers/information_helper.rb
module InformationHelper
end

GymFit/app/helpers/obstacles_helper.rb
module ObstaclesHelper
end

GymFit/app/helpers/trainings_helper.rb
module TrainingsHelper
end

GymFit/app/helpers/users_helper.rb
module UsersHelper
end

GymFit/app/views/information/index.html.erb
<div class = "white_bg3">
<div class = "centralizado">
<div class = "titulo">
<h1>Informações</h1>
</div>
<table>
  <thead>
    <tr>
      <th>Alunos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      <dev class = "white_bg">
        <td><%= user.name %></td>
        <td><%= user.weight %></td>
        <td><%= user.height %></td>
        <td><%= user.mass_percentage %></td>
        <td><%= user.fat_percentage %></td>
        <td><%= link_to 'Editar', edit_user_registration_path%></td>
        
      </tr>
      </div>
    <% end %>
  </tbody>
</table>
<div class = "titulo">
<h1>Treinos</h1>
</div>
<table>
  <thead>
    <tr>
      <th>Treinos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.training_type %></td>
        <td><%= link_to 'Edit', edit_training_path(training) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Novo treino',new_training_path  %>

</br> 

<div class = "titulo">
<h1>Exercícios</h1>
</div>
<table>
  <thead>
    <tr>
      <th>Exercícios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.appliance %></td>
        <td><%= exercise.sessions %></td>
        <td><%= exercise.repetition %></td>
        <td><%= link_to 'Show', exercise %></td>
        <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
        <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo exercício', new_exercise_path %>
</div>
</div>