GymFit/config/routes.rb
Rails.application.routes.draw do
  get 'admins/show'
  get 'users/show'
  devise_for :admins
  devise_for :users
  resources :users
  resources :admins
  resources :trainings
  resources :exercises
  resources :obstacles
  resources :goals
  get 'homepage/index'
  get 'info' => 'information#index'
  get 'listaalunos' => 'users#list_users' 

  root 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GymFit/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

GymFit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

GymFit/app/models/exercise.rb
class Exercise < ApplicationRecord
   belongs_to :training
end

GymFit/app/models/goal.rb
class Goal < ApplicationRecord
end

GymFit/app/models/obstacle.rb
class Obstacle < ApplicationRecord
end

GymFit/app/models/training.rb
class Training < ApplicationRecord
   has_many :exercises
end

GymFit/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :training
  has_one :goal
  has_one :obstacle

end

GymFit/app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
    @admin = Admin.find(params[ :id])
  end
end

GymFit/app/controllers/edition_controller.rb
class EditionController < ApplicationController
  def index
  end
end

GymFit/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:goal)
    end
end

GymFit/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

GymFit/app/controllers/obstacles_controller.rb
class ObstaclesController < ApplicationController
  before_action :set_obstacle, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /obstacles
  # GET /obstacles.json
  def index
    @obstacles = Obstacle.all
  end

  # GET /obstacles/1
  # GET /obstacles/1.json
  def show
  end

  # GET /obstacles/new
  def new
    @obstacle = Obstacle.new
  end

  # GET /obstacles/1/edit
  def edit
  end

  # POST /obstacles
  # POST /obstacles.json
  def create
    @obstacle = Obstacle.new(obstacle_params)

    respond_to do |format|
      if @obstacle.save
        format.html { redirect_to @obstacle, notice: 'Obstacle was successfully created.' }
        format.json { render :show, status: :created, location: @obstacle }
      else
        format.html { render :new }
        format.json { render json: @obstacle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /obstacles/1
  # PATCH/PUT /obstacles/1.json
  def update
    respond_to do |format|
      if @obstacle.update(obstacle_params)
        format.html { redirect_to @obstacle, notice: 'Obstacle was successfully updated.' }
        format.json { render :show, status: :ok, location: @obstacle }
      else
        format.html { render :edit }
        format.json { render json: @obstacle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obstacles/1
  # DELETE /obstacles/1.json
  def destroy
    @obstacle.destroy
    respond_to do |format|
      format.html { redirect_to obstacles_url, notice: 'Obstacle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_obstacle
      @obstacle = Obstacle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def obstacle_params
      params.require(:obstacle).permit(:obstacle)
    end
end

GymFit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[ :id])
  end
  def list_users
    @user = User.find(params[ :id])
  end
end

GymFit/app/helpers/admins_helper.rb
module AdminsHelper
end

GymFit/app/helpers/application_helper.rb
module ApplicationHelper
end

GymFit/app/helpers/edition_helper.rb
module EditionHelper
end

GymFit/app/helpers/exercises_helper.rb
module ExercisesHelper
end

GymFit/app/helpers/goals_helper.rb
module GoalsHelper
end

GymFit/app/helpers/homepage_helper.rb
module HomepageHelper
end

GymFit/app/helpers/information_helper.rb
module InformationHelper
end

GymFit/app/helpers/obstacles_helper.rb
module ObstaclesHelper
end

GymFit/app/helpers/trainings_helper.rb
module TrainingsHelper
end

GymFit/app/helpers/users_helper.rb
module UsersHelper
end

GymFit/app/views/obstacles/_form.html.erb
<%= form_with(model: obstacle, local: true) do |form| %>
  <% if obstacle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obstacle.errors.count, "error") %> prohibited this obstacle from being saved:</h2>

      <ul>
        <% obstacle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :obstacle %>
    <%= form.text_field :obstacle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

GymFit/app/views/obstacles/edit.html.erb
<h1>Editing Obstacle</h1>

<%= render 'form', obstacle: @obstacle %>

<%= link_to 'Show', @obstacle %> |
<%= link_to 'Back', obstacles_path %>

GymFit/app/views/obstacles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Obstacles</h1>

<table>
  <thead>
    <tr>
      <th>Obstacle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @obstacles.each do |obstacle| %>
      <tr>
        <td><%= obstacle.obstacle %></td>
        <td><%= link_to 'Show', obstacle %></td>
        <td><%= link_to 'Edit', edit_obstacle_path(obstacle) %></td>
        <td><%= link_to 'Destroy', obstacle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Obstacle', new_obstacle_path %>

GymFit/app/views/obstacles/new.html.erb
<h1>New Obstacle</h1>

<%= render 'form', obstacle: @obstacle %>

<%= link_to 'Back', obstacles_path %>

GymFit/app/views/obstacles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Obstacle:</strong>
  <%= @obstacle.obstacle %>
</p>

<%= link_to 'Edit', edit_obstacle_path(@obstacle) %> |
<%= link_to 'Back', obstacles_path %>